import type { ScanReport } from "../core/types.js";

export function formatAsHtml(report: ScanReport): string {
  const s = report.summary;

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>AgentLens Report – ${escapeHtml(report.agent.name)}</title>
  <style>
    :root { --green: #22c55e; --red: #ef4444; --yellow: #eab308; --blue: #3b82f6; --gray: #6b7280; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 900px; margin: 2rem auto; padding: 0 1rem; color: #1f2937; }
    h1 { color: #0891b2; }
    .summary { display: flex; gap: 1rem; margin: 1.5rem 0; }
    .stat { padding: 1rem; border-radius: 0.5rem; background: #f3f4f6; text-align: center; flex: 1; }
    .stat .num { font-size: 2rem; font-weight: bold; }
    .stat.errors .num { color: var(--red); }
    .stat.warnings .num { color: var(--yellow); }
    .stat.passed .num { color: var(--green); }
    .category { margin: 1.5rem 0; border: 1px solid #e5e7eb; border-radius: 0.5rem; overflow: hidden; }
    .category-header { padding: 0.75rem 1rem; font-weight: bold; background: #f9fafb; border-bottom: 1px solid #e5e7eb; }
    .result { padding: 0.5rem 1rem; border-bottom: 1px solid #f3f4f6; display: flex; align-items: flex-start; gap: 0.5rem; }
    .result:last-child { border-bottom: none; }
    .icon { width: 1.25rem; flex-shrink: 0; }
    .pass { color: var(--green); }
    .error { color: var(--red); }
    .warning { color: var(--yellow); }
    .info { color: var(--blue); }
    .rule-id { color: var(--gray); font-size: 0.8rem; margin-left: auto; white-space: nowrap; }
    .details { color: var(--gray); font-size: 0.85rem; margin-left: 1.75rem; }
    .meta { color: var(--gray); font-size: 0.9rem; }
  </style>
</head>
<body>
  <h1>AgentLens Scan Report</h1>
  <p class="meta">
    <strong>Agent:</strong> "${escapeHtml(report.agent.name)}"
    ${report.agent.schemaVersion ? `| <strong>Schema:</strong> ${escapeHtml(report.agent.schemaVersion)}` : ""}
    ${report.agent.metadata?.publisher ? `| <strong>Publisher:</strong> ${escapeHtml(report.agent.metadata.publisher)}` : ""}
  </p>
  <p class="meta">
    <strong>Source:</strong> ${report.agent.source.type === "local" ? `Local → ${escapeHtml(report.agent.source.filePath)}` : report.agent.source.type === "remote-dataverse" ? `Dataverse → ${escapeHtml(report.agent.source.botId)}` : `Remote → ${escapeHtml(report.agent.source.packageId)}`}
    | <strong>Scanned:</strong> ${escapeHtml(report.timestamp)}
  </p>

  <div class="summary">
    <div class="stat passed"><div class="num">${s.passed}/${s.totalChecks}</div><div>Passed</div></div>
    <div class="stat errors"><div class="num">${s.errors}</div><div>Errors</div></div>
    <div class="stat warnings"><div class="num">${s.warnings}</div><div>Warnings</div></div>
    <div class="stat"><div class="num">${s.infos}</div><div>Infos</div></div>
  </div>

  ${report.categories.map((cat) => `
  <div class="category">
    <div class="category-header">${escapeHtml(cat.name)} (${cat.passed}/${cat.total})</div>
    ${cat.results.map((r) => `
    <div class="result">
      <span class="icon ${r.passed ? "pass" : r.severity}">${r.passed ? "✓" : r.severity === "error" ? "✗" : r.severity === "warning" ? "⚠" : "ℹ"}</span>
      <span>${escapeHtml(r.message)}</span>
      <span class="rule-id">${escapeHtml(r.ruleId)}</span>
    </div>
    ${r.details && !r.passed ? `<div class="details">→ ${escapeHtml(r.details)}</div>` : ""}
    `).join("")}
  </div>
  `).join("")}

  <p class="meta" style="margin-top: 2rem; text-align: center;">
    Generated by <a href="https://github.com/user/agentlens">AgentLens</a>
  </p>
</body>
</html>`;
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
