import type { ScanReport, CategoryReport, DiffReport } from "../core/types.js";

export function formatAsMarkdown(report: ScanReport): string {
  const lines: string[] = [];

  lines.push(`# CALT Scan Report`);
  lines.push("");
  lines.push(`**Agent:** "${report.agent.name}"`);
  if (report.agent.schemaVersion) {
    lines.push(`**Schema:** ${report.agent.schemaVersion}`);
  }
  if (report.agent.source.type === "local") {
    lines.push(`**Source:** Local → \`${report.agent.source.filePath}\``);
  } else if (report.agent.source.type === "remote-dataverse") {
    lines.push(`**Source:** Dataverse → \`${report.agent.source.botId}\``);
  } else {
    lines.push(`**Source:** Remote (Tenant) → \`${report.agent.source.packageId}\``);
  }
  if (report.agent.metadata) {
    const m = report.agent.metadata;
    if (m.publisher) lines.push(`**Publisher:** ${m.publisher}`);
    if (m.version) lines.push(`**Version:** ${m.version}`);
  }
  lines.push(`**Scanned:** ${report.timestamp}`);
  lines.push("");

  // Summary
  const s = report.summary;
  lines.push(`## Summary`);
  lines.push("");
  lines.push(`| Metric | Count |`);
  lines.push(`|--------|-------|`);
  lines.push(`| Total Checks | ${s.totalChecks} |`);
  lines.push(`| Passed | ${s.passed} |`);
  lines.push(`| Errors | ${s.errors} |`);
  lines.push(`| Warnings | ${s.warnings} |`);
  lines.push(`| Infos | ${s.infos} |`);
  lines.push("");

  // Categories
  for (const cat of report.categories) {
    lines.push(formatCategoryMarkdown(cat));
  }

  lines.push("---");
  lines.push("*Generated by [CALT](https://github.com/stephanbisser/calt)*");

  return lines.join("\n");
}

function formatCategoryMarkdown(cat: CategoryReport): string {
  const lines: string[] = [];
  const icon = cat.results.some((r) => !r.passed && r.severity === "error")
    ? "❌"
    : cat.results.some((r) => !r.passed && r.severity === "warning")
      ? "⚠️"
      : "✅";

  lines.push(`## ${icon} ${cat.name} (${cat.passed}/${cat.total})`);
  lines.push("");
  lines.push(`| Status | Rule | Message |`);
  lines.push(`|--------|------|---------|`);

  for (const r of cat.results) {
    const status = r.passed ? "✅" : severityEmoji(r.severity);
    lines.push(`| ${status} | \`${r.ruleId}\` | ${r.message} |`);
  }

  lines.push("");
  return lines.join("\n");
}

function severityEmoji(severity: string): string {
  switch (severity) {
    case "error": return "❌";
    case "warning": return "⚠️";
    case "info": return "ℹ️";
    default: return "·";
  }
}

export function formatMultipleAsMarkdown(reports: ScanReport[]): string {
  const parts = reports.map((r) => formatAsMarkdown(r));
  return parts.join("\n\n---\n\n");
}

export function formatDiffAsMarkdown(report: DiffReport): string {
  const lines: string[] = [];

  lines.push("# CALT Diff Report");
  lines.push("");
  lines.push(`**Agent A:** "${report.agentA.name}"`);
  lines.push(`**Agent B:** "${report.agentB.name}"`);
  lines.push(`**Compared:** ${report.timestamp}`);
  lines.push("");

  if (report.sections.length === 0) {
    lines.push("No differences found. Agents are identical.");
    lines.push("");
    return lines.join("\n");
  }

  for (const section of report.sections) {
    const icon = section.changeType === "added" ? "+" : section.changeType === "removed" ? "-" : section.changeType === "modified" ? "~" : "=";
    lines.push(`## ${icon} ${section.name}`);
    lines.push("");
    lines.push("| Change | Field | Value |");
    lines.push("|--------|-------|-------|");

    for (const detail of section.details) {
      const changeIcon = detail.changeType === "added" ? "+" : detail.changeType === "removed" ? "-" : detail.changeType === "modified" ? "~" : "=";
      const value = detail.changeType === "modified"
        ? `~~${truncateMd(detail.valueA ?? "")}~~ → ${truncateMd(detail.valueB ?? "")}`
        : truncateMd(detail.valueA ?? detail.valueB ?? "");
      lines.push(`| ${changeIcon} | \`${detail.field}\` | ${value} |`);
    }

    lines.push("");
  }

  // Summary
  const s = report.summary;
  lines.push("## Summary");
  lines.push("");
  lines.push(`| Metric | Count |`);
  lines.push(`|--------|-------|`);
  lines.push(`| Total Changes | ${s.totalChanges} |`);
  lines.push(`| Additions | ${s.additions} |`);
  lines.push(`| Removals | ${s.removals} |`);
  lines.push(`| Modifications | ${s.modifications} |`);
  lines.push("");

  lines.push("---");
  lines.push("*Generated by [CALT](https://github.com/stephanbisser/calt)*");

  return lines.join("\n");
}

function truncateMd(value: string): string {
  const escaped = value.replace(/\|/g, "\\|").replace(/\n/g, " ");
  if (escaped.length <= 80) return escaped;
  return escaped.slice(0, 77) + "...";
}
