import * as vscode from "vscode";
import * as path from "node:path";
import * as fs from "node:fs/promises";

type WorkflowKind = "github" | "azure-devops";

const WORKFLOWS: Record<
  WorkflowKind,
  { label: string; description: string; relativePath: string; content: () => string }
> = {
  github: {
    label: "GitHub Actions",
    description: "Adds .github/workflows/calt.yml with scan + SARIF upload to Code Scanning.",
    relativePath: ".github/workflows/calt.yml",
    content: githubWorkflow,
  },
  "azure-devops": {
    label: "Azure DevOps Pipeline",
    description: "Adds azure-pipelines-calt.yml.",
    relativePath: "azure-pipelines-calt.yml",
    content: azureDevopsPipeline,
  },
};

export function registerCiWorkflowCommand(context: vscode.ExtensionContext): void {
  context.subscriptions.push(
    vscode.commands.registerCommand("calt.generateCiWorkflow", async () => {
      await runGenerator();
    }),
  );
}

async function runGenerator(): Promise<void> {
  const folders = vscode.workspace.workspaceFolders ?? [];
  if (folders.length === 0) {
    void vscode.window.showErrorMessage("CALT: open a folder before generating a CI workflow.");
    return;
  }
  const folder =
    folders.length === 1
      ? folders[0]
      : await vscode.window.showWorkspaceFolderPick({
          placeHolder: "Select the workspace folder",
        });
  if (!folder) return;

  const items: (vscode.QuickPickItem & { id: WorkflowKind })[] = (
    Object.keys(WORKFLOWS) as WorkflowKind[]
  ).map((id) => ({ id, label: WORKFLOWS[id].label, description: WORKFLOWS[id].description }));
  const pick = await vscode.window.showQuickPick(items, {
    placeHolder: "Which CI provider?",
    ignoreFocusOut: true,
  });
  if (!pick) return;

  const wf = WORKFLOWS[pick.id];
  const target = path.join(folder.uri.fsPath, wf.relativePath);
  try {
    await fs.access(target);
    const choice = await vscode.window.showWarningMessage(
      `${wf.relativePath} already exists. Overwrite?`,
      { modal: true },
      "Overwrite",
      "Cancel",
    );
    if (choice !== "Overwrite") return;
  } catch {
    // File doesn't exist — proceed.
  }
  await fs.mkdir(path.dirname(target), { recursive: true });
  await fs.writeFile(target, wf.content(), "utf8");
  const doc = await vscode.workspace.openTextDocument(target);
  await vscode.window.showTextDocument(doc);
  void vscode.window.showInformationMessage(
    `CI workflow generated at ${vscode.workspace.asRelativePath(target)}.`,
  );
}

function githubWorkflow(): string {
  return `# Generated by CALT — Copilot Agent Lint Tool
name: CALT

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  security-events: write   # required for SARIF upload to Code Scanning

jobs:
  calt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install CALT
        run: npm install -g calt-cli
      - name: Run CALT scan
        run: calt scan . --format sarif --output calt.sarif || true
      - name: Upload CALT findings as artifact
        uses: actions/upload-artifact@v4
        with:
          name: calt-sarif
          path: calt.sarif
      - name: Upload SARIF to GitHub Code Scanning
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: calt.sarif
          category: calt
      - name: Fail the build on errors
        run: calt scan . --format json | node -e "let s='';process.stdin.on('data',d=>s+=d).on('end',()=>{const j=JSON.parse(s);if((j.summary?.errors||0)>0)process.exit(1)})"
`;
}

function azureDevopsPipeline(): string {
  return `# Generated by CALT — Copilot Agent Lint Tool
trigger:
  branches:
    include: [main]

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "20.x"
  - script: npm install -g calt-cli
    displayName: Install CALT
  - script: calt scan . --format sarif --output calt.sarif
    displayName: Run CALT scan
    continueOnError: true
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: calt.sarif
      artifactName: calt-sarif
    displayName: Publish SARIF artifact
  - script: calt scan . --format json | node -e "let s='';process.stdin.on('data',d=>s+=d).on('end',()=>{const j=JSON.parse(s);if((j.summary?.errors||0)>0)process.exit(1)})"
    displayName: Fail on errors
`;
}
